server.port=5000
spring.data.mongodb.uri=mongodb://localhost:27017/personalfinance
spring.data.mongodb.database=personalfinance
jwt.secret=supersecretjwtkey_please_change_in_production
jwt.expirationMs=86400000
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG  